"""Content-level tests for the five generated MoE skills.

Validates that the real skills shipped under ``skills/`` are discoverable
by the repository loader, well-formed (frontmatter + required
subdirectories), that every tool script answers ``--help`` with exit code
0, and that no meta-noise strings leak into the skill markdown content.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

from moe_agentic.skill_loader import SkillLoader

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

EXPECTED_SKILLS: tuple[str, ...] = (
    "moe-architecture",
    "moe-training",
    "moe-debugging",
    "moe-performance",
    "moe-benchmarking",
)

REQUIRED_SUBDIRS: dict[str, tuple[str, ...]] = {
    "moe-architecture": ("knowledge", "tools", "examples"),
    "moe-training": ("configs", "tools", "knowledge", "examples"),
    "moe-debugging": ("analyzers", "tools", "knowledge", "examples"),
    "moe-performance": ("profilers", "tools", "knowledge", "examples"),
    "moe-benchmarking": ("evaluators", "knowledge", "examples"),
}

TOOL_SCRIPTS: tuple[str, ...] = (
    "moe-architecture/tools/moe_calculator.py",
    "moe-training/tools/memory_estimator.py",
    "moe-debugging/analyzers/router_distribution.py",
    "moe-debugging/analyzers/loss_analyzer.py",
    "moe-debugging/analyzers/expert_utilization.py",
    "moe-debugging/tools/diagnosis_report.py",
    "moe-performance/profilers/throughput_profiler.py",
    "moe-performance/tools/bottleneck_rank.py",
    "moe-benchmarking/evaluators/score_architecture.py",
    "moe-benchmarking/evaluators/score_debugging.py",
)

META_NOISE_TOKENS: tuple[str, ...] = ("Generated by", "TODO", "FIXME", "TBD")


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def skills_root() -> Path:
    """Return the repo-relative ``skills`` directory."""
    return Path(__file__).resolve().parents[1] / "skills"


@pytest.fixture(scope="module")
def loader(skills_root: Path) -> SkillLoader:
    """Return a SkillLoader pointed at the repository skills directory."""
    return SkillLoader(skills_dir=skills_root)


# ---------------------------------------------------------------------------
# Discovery / validation
# ---------------------------------------------------------------------------


class TestDiscovery:
    """SkillLoader must discover and validate the five real skills."""

    def test_all_five_skills_discovered(self, loader: SkillLoader) -> None:
        """Every expected skill name appears in the discovery set."""
        discovered = loader.discover()
        assert set(EXPECTED_SKILLS) <= set(discovered)

    def test_validate_all_reports_no_errors(self, loader: SkillLoader) -> None:
        """validate_all() must return an empty error mapping."""
        assert loader.validate_all() == {}


# ---------------------------------------------------------------------------
# Frontmatter / body
# ---------------------------------------------------------------------------


class TestSkillContent:
    """Frontmatter and body requirements for each real skill."""

    @pytest.mark.parametrize("name", EXPECTED_SKILLS)
    def test_metadata_has_required_fields(
        self, loader: SkillLoader, name: str
    ) -> None:
        """Frontmatter exposes name, description, and metadata fields."""
        meta = loader.load(name).metadata
        assert meta.name == name
        assert meta.description
        assert meta.license
        assert meta.compatibility
        assert meta.metadata
        assert meta.argument_hint

    @pytest.mark.parametrize("name", EXPECTED_SKILLS)
    def test_frontmatter_name_matches_directory(
        self, loader: SkillLoader, name: str
    ) -> None:
        """Frontmatter name must equal the containing directory name."""
        skill = loader.load(name)
        assert skill.name == skill.source_dir.name == name

    @pytest.mark.parametrize("name", EXPECTED_SKILLS)
    def test_content_body_is_non_empty(
        self, loader: SkillLoader, name: str
    ) -> None:
        """The markdown body after the frontmatter must be non-empty."""
        assert loader.load(name).content.strip()

    @pytest.mark.parametrize("name", EXPECTED_SKILLS)
    def test_required_subdirectories_exist(
        self, loader: SkillLoader, name: str
    ) -> None:
        """Every expected subdirectory must exist under the skill dir."""
        skill = loader.load(name)
        for subdir in REQUIRED_SUBDIRS[name]:
            assert (skill.source_dir / subdir).is_dir(), (
                f"{name} is missing required subdirectory {subdir!r}"
            )


# ---------------------------------------------------------------------------
# Tool smoke tests
# ---------------------------------------------------------------------------


class TestToolSmoke:
    """Every tool script must answer ``--help`` with exit code 0."""

    @pytest.mark.parametrize("rel_path", TOOL_SCRIPTS)
    def test_tool_help_exits_zero(
        self, skills_root: Path, rel_path: str
    ) -> None:
        """Running a tool script with --help must exit with status 0."""
        script = skills_root / rel_path
        if not script.is_file():
            pytest.skip(f"tool script not present: {rel_path}")
        result = subprocess.run(
            [sys.executable, str(script), "--help"],
            capture_output=True,
            text=True,
            check=False,
        )
        assert result.returncode == 0, result.stderr


# ---------------------------------------------------------------------------
# Meta-noise
# ---------------------------------------------------------------------------


class TestNoMetaNoise:
    """Skill markdown must be free of generation/placeholder markers."""

    @pytest.mark.parametrize("name", EXPECTED_SKILLS)
    def test_no_meta_noise_in_markdown(
        self, skills_root: Path, name: str
    ) -> None:
        """SKILL.md, knowledge/, and examples/ must not contain noise."""
        skill_dir = skills_root / name
        md_files: list[Path] = [skill_dir / "SKILL.md"]
        for subdir in ("knowledge", "examples"):
            sub_path = skill_dir / subdir
            if sub_path.is_dir():
                md_files.extend(sorted(sub_path.glob("*.md")))
        assert md_files, f"no markdown files found for {name}"
        for md_file in md_files:
            text = md_file.read_text(encoding="utf-8")
            for token in META_NOISE_TOKENS:
                assert token not in text, f"{token!r} found in {md_file}"
